package com.vince.vchat12.data;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.vince.vchat12.data.UserDataDao;
import com.vince.vchat12.data.FriendDataDao;
import com.vince.vchat12.data.GroupDataDao;
import com.vince.vchat12.data.MsgDataDao;
import com.vince.vchat12.data.DialogueDataDao;
import com.vince.vchat12.data.CircleWebDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDataDao.createTable(db, ifNotExists);
        FriendDataDao.createTable(db, ifNotExists);
        GroupDataDao.createTable(db, ifNotExists);
        MsgDataDao.createTable(db, ifNotExists);
        DialogueDataDao.createTable(db, ifNotExists);
        CircleWebDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDataDao.dropTable(db, ifExists);
        FriendDataDao.dropTable(db, ifExists);
        GroupDataDao.dropTable(db, ifExists);
        MsgDataDao.dropTable(db, ifExists);
        DialogueDataDao.dropTable(db, ifExists);
        CircleWebDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDataDao.class);
        registerDaoClass(FriendDataDao.class);
        registerDaoClass(GroupDataDao.class);
        registerDaoClass(MsgDataDao.class);
        registerDaoClass(DialogueDataDao.class);
        registerDaoClass(CircleWebDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
