package com.vince.vchat12.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP_DATA".
 */
public class GroupData {

    private String objectId;
    private java.util.Date updateTime;
    private String groupName;

    public GroupData() {
    }

    public GroupData(String objectId) {
        this.objectId = objectId;
    }

    public GroupData(String objectId, java.util.Date updateTime, String groupName) {
        this.objectId = objectId;
        this.updateTime = updateTime;
        this.groupName = groupName;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
